# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.0'

gem 'aws-sdk-s3', '~> 1.146', '>= 1.146.1'
gem 'bootsnap', require: false
gem 'image_processing', '~> 1.2'
gem 'nokogiri', '~> 1.12', '>= 1.12.4'
gem 'puma', '>= 5.0'
gem 'rack-cors', '~> 2.0', '>= 2.0.2'
gem 'rails', '~> 7.1.3', '>= 7.1.3.2'
gem 'ruby-vips', '~> 2.2', '>= 2.2.1'
gem 'sqlite3', '~> 1.4'
gem 'tzinfo-data'
gem 'will_paginate', '~> 4.0'

group :development, :test do
  gem 'debug', platforms: %i[mri mswin mswin64 mingw x64_mingw]
  gem 'dotenv', '~> 3.1'
  gem 'rspec-rails', '~> 6.1', '>= 6.1.2'
end

group :development do
  gem 'error_highlight', '>= 0.4.0', platforms: [:ruby]
end
